### ISSUE TITLE
[Feature] Add an external source for movie search/downloads 

### ISSUE THREAD

**Issue by PreciousOritsedere** [creativecommons/search#100]
## Problem

Seeing that there’s already an external source for music, adding an external source for movies will give the users an extra variety of options.

![AA8E239C-9D1D-41E0-A0EE-16FB1E01CE3C](https://user-images.githubusercontent.com/104203890/195985746-65210c4a-87ad-4bdf-a33c-59c5cd73d5af.jpeg)

## Description
This is feature is aimed towards adding [Fzmovies](https://fzmovies.net/) as an external source for movies.

## Implementation

I will add this as an additional search source for movies
- [x] I would be interested in implementing this feature.

**Comment by PreciousOritsedere** [comment]
@possumbilities if this issue is approved, can you please assign to me? I’d love to work on it 😊

**Comment by dipanshuraz** [comment]
Hi @PreciousOritsedere, I'm outreachy applicant, I'm also interested to pick this up. maybe we can do this together,
Please let me know 😄

**Comment by PreciousOritsedere** [comment]
> Hi @PreciousOritsedere, I'm outreachy applicant, I'm also interested to pick this up. maybe we can do this together,
> Please let me know 😄

Hey! Sure. I’d be happy to collaborate with you in this.

**Comment by possumbilities** [comment]
I'm closing this since my understanding of FZMovies is that it is not a CC Licensed source of movies, but is instead considered an illegal non-licensed download site.

Please keep in mind we only want to add engines that offer legitimate Creative Commons licensed results.
