### ISSUE TITLE
[Feature] remove section Try Openverse: Openly Licensed Images, Audio and More.

### ISSUE THREAD

**Issue by ImaJin14** [creativecommons/search#104]
## Problem

Try [Openverse](https://wordpress.org/openverse/?referrer=creativecommons.org): Openly Licensed Images, Audio and More. wont be required as openverse will be added to CC Search Portal engines
## Description

as openverse will be added to cc search portal engines, there wont be need to allow the statement that prompts users to try openverse
## Alternatives

could be left same which will reduce the usage of the search engine on the portal
## Implementation

- [ x] I would be interested in implementing this feature.

**Comment by adetyaz** [comment]
hello @ImaJin14 I'm an outreachy applicant,  I would be interested in implementing this feature. or at least join you if you are already

**Comment by ImaJin14** [comment]
> hello @ImaJin14 I'm an outreachy applicant,  I would be interested in implementing this feature. or at least join you if you are already

Let the project status change fes

**Comment by possumbilities** [comment]
This is blocked until the Openverse engine gets properly added in.

**Comment by ImaJin14** [comment]
@possumbilities #37 has been merged and hence this issue can be worked on now with your approval:)
