### ISSUE TITLE
[Bug] Improve responsiveness on Tablet screens

### ISSUE THREAD

**Issue by adetyaz** [creativecommons/search#106]
## Description
When the project is run on a tablet screen it should be properly responsive with no overlapping elements.

## Reproduction

1. Run the project locally
2. Change the screen size to the tablet viewport 
3. See the search portal text overlapping the button

## Expectation
The we interface should be responsive on all screen sizes

## Screenshots

![responsiveness bug](https://user-images.githubusercontent.com/17833631/196157276-1d4bd134-4536-4685-868b-e63076254daa.PNG)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
This is already related to an existing issue: 
* #88
