### ISSUE TITLE
[Feature] Add Sketchfab as an External Source

### ISSUE THREAD

**Issue by dullbenz** [creativecommons/search#107]
## Problem
This is a sub-issue steming out from Issue: [[Feature] Additional source suggestions](https://github.com/creativecommons/search/issues/48) #48
The goal is to add a good number of external sources to give users a variety of results from diverse legal sources.

## Description
From the additional sources list of Openverse available in the file [get-additional-sources.ts](https://github.com/WordPress/openverse-frontend/blob/main/src/utils/get-additional-sources.ts#L61) mentioned in #48, I picked out [Sketchfab](https://sketchfab.com/) among the sources listed. Sketchfab offers both free and paid 3D model designs for its users to choose from and has a wide variety of options.

Screenshot from Sketchfab Website
![image](https://user-images.githubusercontent.com/40190640/196288163-b32c6786-908c-4e80-b8f3-4c46253eb206.png)

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by PreciousOritsedere** [comment]
Hello @possumbilities can you please assign this issue to me? I’d love to work on it 😊

**Comment by ImaJin14** [comment]
> Hello @possumbilities can you please assign this issue to me? I want to start working on it now😊

@dullbenz indicated he'll love to work on it while opening this issue:)
