### ISSUE TITLE
[Feature] Clicking search box before typing.

### ISSUE THREAD

**Issue by VictoriaAjala** [creativecommons/search#120]
## Problem
when u click on any of the search box apart from ccMixter before typing, then you click enter. It does not search based on the search box you've clicked, instead it automatically searches it on ccMixter.

## Description
When you click on any of the search box before typing what you want to search and then click enter. It searches for what you want based on the search box you've selected

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by ImaJin14** [comment]
@VictoriaAjala I think this is a great issue but it'll be blocked by #108 by @TimidRobot

**Comment by dikehprosper** [comment]
@VictoriaAjala there is an issue on that created already

**Comment by ImaJin14** [comment]
> @VictoriaAjala there is an issue on that created already 

Please reference it here so she can see it!!!

**Comment by possumbilities** [comment]
I tend to agree with the comments that this is likely at a minimum blocked by #93, if not a duplicate. I'm going to block for now, but if the evolution of #93 turns into covering this then it would likely close as a duplicate.

**Comment by possumbilities** [comment]
Resolved in new site merge: https://github.com/creativecommons/search/pull/206
