### ISSUE TITLE
CC search portal image not responsive for small devices

### ISSUE THREAD

**Issue by Biki-das** [creativecommons/search#121]
## Description
The cc search portal images does not seem to be responsive for small devices as the images just overflows
## Reproduction
![CC Search Portal — Mozilla Firefox 10_20_2022 2_40_38 PM](https://user-images.githubusercontent.com/72331432/196907275-c6f410d1-83d3-42c9-8cfa-e00f664041e7.png)
![CC Search Portal — Mozilla Firefox 10_20_2022 2_40_17 PM](https://user-images.githubusercontent.com/72331432/196907341-caca1308-ed09-4855-9b6a-f81bbc32a982.png)

## Expectation
The image should be responsive across all type of devices

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Biki-das** [comment]
@possumbilities the fix is simple which is making the image width 100%, but the problem that i arrived is it also affects the footer social link images too and the css for the same is present in cc-wp/css/style.css where it says not to edit anything, any pointer would be appreciated for me to figure this out

**Comment by ImaJin14** [comment]
@Biki-das I think this is similar to #106 by @adetyaz which was closed as a duplicate to #88 by @marvisjaja 


I think this issue too will be closed:)

**Comment by dikehprosper** [comment]
@Biki-das  an issue in this has already been raised

**Comment by possumbilities** [comment]
Thanks for the efforts, I do appreciate your enthusiasm, but as others have stated already this is definitely a duplicate, already covered in #88. Closing.

**Comment by Biki-das** [comment]
Thanks @possumbilities for assigning me
