### ISSUE TITLE
[Feature] Add outline to checkbox input to improve accessibility

### ISSUE THREAD

**Issue by mbonamensa** [creativecommons/search#126]
## Problem

There's an `outline: none;` set on all inputs when focused. This can cause accessibility issues for keyboard users. This feature will make the inputs, especially the checkbox input more accessible by styling its focused state so that there is a visible outline. 

In this screenshot, the checkbox is focused using the keyboard tab, there's a light blue focus around it which is barely visible.
![Screenshot (49)](https://user-images.githubusercontent.com/85899285/196973058-229d9c32-faea-4cc1-af85-4cd74e5fed24.png)

Compare to this screenshot that visibly shows that the checkbox is focused
![Screenshot (50)](https://user-images.githubusercontent.com/85899285/196976768-4c01229a-ed63-4eb6-beb4-b0b30844ea1e.png)

## Description

Usually, setting an `outline: none;` is not the best practice as it creates accessibility issues, especially for users who navigate the website using keyboards only. This feature will style the outline instead of setting it to none to be consistent with the website style. 

## Alternatives

Comments in the cc-wp/css/style.css file mention that the file should not be edited. An alternative will be to style the checkbox only instead, (which is the main visible issue on the website), which can be targeted using the id selector `#permissions input` in the creative-commons-search/style.css file.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by mbonamensa** [comment]
Can you please assign me @possumbilities @TimidRobot 
I'm happy to work on this issue to increase the site's accessibility for keyboard users ❤️

**Comment by ImaJin14** [comment]
@mbonamensa I think the checkbox outline themselves quite well... If not checked they don't show blue but rather an empty check box![Screenshot_20221020-174748.png](https://user-images.githubusercontent.com/112979436/197009781-99f06d0d-89b5-48e0-8d76-5de164d1078f.png)

**Comment by mbonamensa** [comment]
@ImaJin14 Thanks for contributing your thoughts.

The outline seems okay when the boxes are not checked and in this case, the site automatically checks the boxes onload. This is okay and maybe insignificant for people who navigate the site using their mouse. It however may be an issue for others who use keyboards only. 
I found this issue when I realized I had skipped over the checkboxes a couple of times because I did not see it in focus when using the keyboard tab. 
It may seem insignificant but may go a long way to make the site a little more user-friendly for keyboard users. 
This article talks about how removing outlines on inputs impact accessibility and suggests alternatives: https://www.a11yproject.com/posts/never-remove-css-outlines/ 
You can take a look at it for reference.

I'll however want to know what @possumbilities and @TimidRobot think about this and if it's okay to work on.

**Comment by mbonamensa** [comment]
You're absolutely right. Leaving them to browser defaults would be the best thing to do. I suggested styling them in addition to the removal just in case the aesthetics of the page were to remain intact. But I think full accessibility over aesthetics right? Lol

**Comment by possumbilities** [comment]
@mbonamensa yes, full Accessibility the whole way.

**Comment by mbonamensa** [comment]
I'll get to work on this, thanks @possumbilities

**Comment by mbonamensa** [comment]
@possumbilities The file (cc-wp/css/style.css) containing general styles for the `input` is not to be edited as per the comments. What do you suggest I do?

**Comment by possumbilities** [comment]
@mbonamensa there's a file in the root directory entitled `style.css` it occurs after the other file and thus overrides it. Any rules you place within that file with [adequate specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) should work.

**Comment by mbonamensa** [comment]
@possumbilities  Awesome. It does. The issue I raised only targets the checkboxes, can I include the text input as well? I also used the `:focus-visible` selector which means the outline shows for keyboard users only and not mouse users. Using it on the text input will however show the outline for both users. Thoughts?

**Comment by possumbilities** [comment]
@mbonamensa since the route of solutions is likely to differ for the text input, let's keep the scope of this Issue to the checkbox. 

But you can make another Issue for the text input if its not already covered in any other Issues, and we could strategize further from there.

**Comment by mbonamensa** [comment]
@possumbilities Alright then.

**Comment by mbonamensa** [comment]
@possumbilities I see that #85 and #93 target the design of the text input and there seems to be more research to be done before the issues can be triaged. At the moment I think the text input focus is visible enough and is the first user contact whenever the page is loaded. However, I think the issue of accessibility, where the focus styles can be reverted to browser defaults can be addressed in the above issues after further research has been done. Unless it's considered a high priority then I can raise the issue of the text input right away.

Also, I did some checks for inputs on the cc global sites and realized something interesting. On the contact page, (https://creativecommons.org/about/contact/) the outline is set to zero, and focus styles are set. The newsletter subscription page (https://mail.creativecommons.org/subscribe) however has the input focus styles left to browser defaults. Is there a reason for this?

**Comment by possumbilities** [comment]
@mbonamensa I think it's specific enough you could make an Issue about it. 

As for those links, there's definitely inconsistency on other sites, and that likely needs to be addressed, but that's out of the scope of this particular repository. But thank you for raising it nonetheless. ❤️

**Comment by mbonamensa** [comment]
Okay, thank you @possumbilities 
Is there a design document or brand guidelines that CC global follows though?

**Comment by possumbilities** [comment]
@mbonamensa That would be Vocabulary, Creative Commons Design System, https://github.com/creativecommons/vocabulary BUT its in flux at the moment so it's mostly correct, but not 100% in every case.
