### ISSUE TITLE
[Feature] Improving the skip navigation link

### ISSUE THREAD

**Issue by Biki-das** [creativecommons/search#129]
## Problem
The current skip navigation link seems a little off, i feel we can improve it 

![CC Search Portal — Mozilla Firefox 10_20_2022 11_40_54 PM](https://user-images.githubusercontent.com/72331432/197026350-524a1407-d5d8-4a32-9d1a-cc812f2c5d5c.png)

I played around and made something like this 
![CC Search Portal — Mozilla Firefox 10_20_2022 11_51_05 PM](https://user-images.githubusercontent.com/72331432/197027753-9a895fda-a1e3-40ba-b590-924ecf4f05a5.png)

## Description
This would make it more easy to see and interact with the link
## Implementation

- [x] I would be interested in implementing this feature.

**Comment by ImaJin14** [comment]
I don't think this issue is valid as the live site doesn't have a skip navigation bar....


In a nutshell this issue seems invalid:)

**Comment by Biki-das** [comment]
> I don't think this issue isn't valid as the live site doesn't have a skip navigation bar....
> 
> In a nutshell this issue seems invalid:)

Did not got what are you saying the site does have a skip navigation link

**Comment by ImaJin14** [comment]
> > I don't think this issue isn't valid as the live site doesn't have a skip navigation bar....
> > 
> > In a nutshell this issue seems invalid:)
> 
> Did not got what are you saying the site does have a skip navigation link

![Screenshot_20221020-193636.png](https://user-images.githubusercontent.com/112979436/197030524-25775b5d-77be-4e02-abb8-bc2d3e7323a9.png)


Do u see any skip navigation on the header???.... 


The raised issue is invalid:)

**Comment by Biki-das** [comment]
> > > I don't think this issue isn't valid as the live site doesn't have a skip navigation bar....
> > > In a nutshell this issue seems invalid:)
> > 
> > 
> > Did not got what are you saying the site does have a skip navigation link
> 
> ![Screenshot_20221020-193636.png](https://user-images.githubusercontent.com/112979436/197030524-25775b5d-77be-4e02-abb8-bc2d3e7323a9.png)
> 
> Do u see any skip navigation on the header???....
> 
> The raised issue is invalid:)

press tab to see it, this is a accessibility feature

**Comment by possumbilities** [comment]
I think the confusion here is that the `skip navigation` button _is_ present, but there isn't any navigation for it to skip, so its existence might not be needed? Perhaps that's a different angle to consider for this issue?

**Comment by ImaJin14** [comment]
@possumbilities your right and I think the button be removed....

**Comment by muditgaur-1009** [comment]
can anyone tell me whether to change the navigation button or if it is not linked to anything else

**Comment by possumbilities** [comment]
Resolved in new site merge: https://github.com/creativecommons/search/pull/206
