### ISSUE TITLE
[Feature] Add Vimeo as an  additional External Source

### ISSUE THREAD

**Issue by Rubadel** [creativecommons/search#131]
## Problem
This is a sub-issue out of https://github.com/creativecommons/search/issues/48 

## Description
From the additional sources list in the file [get-additional-sources.ts](https://github.com/WordPress/openverse-frontend/blob/main/src/utils/get-additional-sources.ts#L61) that mentioned in https://github.com/creativecommons/search/issues/48, I choose the[Vimeo](https://vimeo.com/search) which provide more of video options free and paid.

<img width="1440" alt="Screen Shot 1444-03-25 at 4 47 54 AM" src="https://user-images.githubusercontent.com/66481905/197092103-eb8b3bad-f50f-41f1-a3b6-0f1cd87ef4cd.png">

## Additional context
That provide more resource for the Creative Commons engine 

## Implementation

- [x] I would be interested in implementing this feature.
Could you assign me @TimidRobot @possumbilities

**Comment by SilasEze** [comment]
I would be interested in implementing this feature.
Could you assign me @TimidRobot @possumbilities

**Comment by possumbilities** [comment]
In reference to #160 to fully resolve this Issue the appropriate `aria-label` will need to be added to the engine button.
