### ISSUE TITLE
[Improvement] <Create a new separate index.html file for the html code in index.php >

### ISSUE THREAD

**Issue by FrancoFrancis** [creativecommons/search#139]
## Problem
Doing this makes it easier to move around the code base, because I had some trouble finding the html code, before I finally found it in the index.php file.

## Description

A new index.html file will be created and the html code in index.php file will be moved into it. So when you need to see the code you will clearly see the index.html file.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by FrancoFrancis** [comment]
Hi @TimidRobot and @possumbilities kindly give a go ahead so I can work on this issue I have created. thanks

**Comment by possumbilities** [comment]
HI @FrancoFrancis thank you for being so enthusiastic, and trying to find ways to improve the codebase! ❤️ 

This is a PHP project, PHP projects generally do not have `index.html` files, they instead will often have an `index.php` file. The file extension indicates what code is within it. An `index.php` file can have PHP & HTML (and any other languages HTML allows) within it, but an `index.html` file cannot have PHP within it, it can have HTML (and CSS and JS).

As the project is still written in PHP, I don't believe it stable to move it out into just an `index.html` file at this time.

**Comment by FrancoFrancis** [comment]
> HI @FrancoFrancis thank you for being so enthusiastic, and trying to find ways to improve the codebase! ❤️
> 
> This is a PHP project, PHP projects generally do not have `index.html` files, they instead will often have an `index.php` file. The file extension indicates what code is within it. An `index.php` file can have PHP & HTML (and any other languages HTML allows) within it, but an `index.html` file cannot have PHP within it, it can have HTML (and CSS and JS).
> 
> As the project is still written in PHP, I don't believe it stable to move it out into just an `index.html` file at this time.


thank you sara, its been a pleasure to learn and contribute. :)
