### ISSUE TITLE
[Feature] <Add Vimeo as an additional External Source > #131

### ISSUE THREAD

**Issue by SilasEze** [creativecommons/search#148]
## Problem
This is a sub-issue out of https://github.com/creativecommons/search/issues/48

## Description
From the additional sources list in the file [get-additional-sources.ts](https://github.com/WordPress/openverse-frontend/blob/main/src/utils/get-additional-sources.ts#L61) that mentioned in https://github.com/creativecommons/search/issues/48, I choose the[Vimeo](https://vimeo.com/search) which provide more of video options free and paid.

## Alternatives
Inline Media:
To embed a Vimeo video as a background video
![Screenshot (31)](https://user-images.githubusercontent.com/93432729/198054075-2d891aa6-26dd-4421-a601-f37790a410ba.png)

## Additional context
 video source url is an special type with "external" word

That provide more resource for the Creative Commons engine

## Implementation
 video source url is an special type with "external" word
- [x] I would be interested in implementing this feature.
- [x] Could you assign me @TimidRobot @possumbilities

**Comment by possumbilities** [comment]
HI and thankyou for your excitement, but this Issue already exists as: 
* #131 

Please be careful to not create duplicate Issues. ❤️ 

Closing as Duplicate.
