### ISSUE TITLE
[Feature] Convert to a static application with modern semantics

### ISSUE THREAD

**Issue by onyijne** [creativecommons/search#152]
## Problem
The code-base is currently written in PHP with its semantics being included from various files and these files do not really do anything different than to add semantics to the page. This makes it impossible to host the application on GitHub pages. 
Also the semantics do not meet current standards, and as such makes it difficult to use with modern accessibility devices and software.

## Description
All the semantics that are currently included from various PHP files in the index.php file will be refactored into a static file paying attention to accessibility and responsiveness of the semantics. 

## Additional context
The application is currently structured more like a WordPress theme

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by onyijne** [comment]
Hi @possumbilities kindly check if this issue can fly, thanks.

**Comment by possumbilities** [comment]
This is a vast Issue covering a lot of scope, and so this Issue should operate at best as a discussion that can generate sub-Issues with more specific aims.

**Comment by PreciousOritsedere** [comment]
I would also like to add that converting the present PHP files into semantic HTML and JavaScript might be necessary as well

**Comment by onyijne** [comment]
> I would also like to add that converting the present PHP files into semantic HTML and JavaScript might be necessary as well

Hi @PreciousOritsedere, yes that’s the task required for Outreachy interns.

**Comment by possumbilities** [comment]
Resolved in new site merge: https://github.com/creativecommons/search/pull/206
