### ISSUE TITLE
[Feature] Add accessible names to search engine buttons

### ISSUE THREAD

**Issue by JennySimen** [creativecommons/search#155]
## Problem

When the platform is analized by the https://web.dev/, we see how we can can improve the accessibility section significantly.

The will address the issue to fix `Buttons do not have an accessible name`. 

Adding accessible names to all the search engines button will significantly improve the accessibility test.

<img width="1248" alt="Screen Shot 2022-10-28 at 10 08 59" src="https://user-images.githubusercontent.com/44881714/198550342-a9bd7f92-4aa2-4b4f-8631-a0100cc208c1.png">

Why do we add this names? `Screen reader users are not able to discern the purpose of elements with role="button" that do not have an accessible name.`

## Description

Adding `aria-label="engine-name"` to all engine buttons would improve this section.

https://dequeuniversity.com/rules/axe/4.4/button-name

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by JennySimen** [comment]
@possumbilities please triage this issue

**Comment by possumbilities** [comment]
@JennySimen I agree this is an Issue, and I'm Ok with this fix as a temporary one, but in general  `aria` attributes are often needed when the rest of the code doesn't conform to a more standard and stable implementation. In this instance what you've discovered is that the more ideal scenario would be the buttons all need to be minimally `<button>` elements, AND that they contain inner text: `<button>engineName</button>`. If they had proper inner text, then the use of `aria` in this instance wouldn't be necessary.

But the current code is not easily refactored that direction, so the next best thing would be the `aria-label` route you've suggested. 

I'm leaving this note here so we can make another Issue after this outlining an additional change to make the buttons operate in a more stable manner in the future (feel free to make that Issue if you want).
