### ISSUE TITLE
[Feature] Refactor Search Engine buttons

### ISSUE THREAD

**Issue by JennySimen** [creativecommons/search#159]
## Problem

The current implementation of the search engine buttons needs refactoring in order to provide a more standard and stable implementation. 

This should also provide better fix for #155. Below is the current structure of the search engine buttons

```
<div class="engine">
       <div class="engineButton">
	  <button onclick="setEngine(this)" name="engine" value="ccmixter" id="ccmixter"></button>
       </div>
      <div class="engineDesc"><label for="ccmixter"><strong>ccMixter</strong><br/>Music</label></div>
</div>
```

## Description

Create minimal `<button>` elements for each search engine AND they should contain inner text: `<button>engineName</button>`.

Reference [this comment](https://github.com/creativecommons/search/issues/155#issuecomment-1297167324) as guide.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by JennySimen** [comment]
@possumbilities please if anything needs to be added to this issues, do let me know so I can update the issues description.

**Comment by ImaJin14** [comment]
If this gets triage I'll love to work on it... Please assign it to me @possumbilities ....

**Comment by mbonamensa** [comment]
Awesome issue raised on #155  @JennySimen  
@possumbilities I would be interested in working on this issue can you please assign me?

**Comment by JennySimen** [comment]
@ImaJin14 @mbonamensa  I think we could assist and encourage those without contributions to pick this up and work on it 🙂

**Comment by mbonamensa** [comment]
@JennySimen Yeah sure, I'll share this in Slack and if after a while no one has, I'd love to work on it.

**Comment by mbonamensa** [comment]
@JennySimen Sure! Happy to work with you on this.

**Comment by JennySimen** [comment]
@possumbilities yes I am

**Comment by mbonamensa** [comment]
@JennySimen how's it going?
Where can I help?

**Comment by JennySimen** [comment]
@mbonamensa it's going quite well, soon creating a PR for the issue

**Comment by possumbilities** [comment]
Resolved in new site merge: https://github.com/creativecommons/search/pull/206
