### ISSUE TITLE
[Bug] Wikimedia Commons card component not properly aligned

### ISSUE THREAD

**Issue by dikehprosper** [creativecommons/search#166]
## Description
Wikimedia commons card component is not properly aligned with other search card component

## Reproduction

1. run the project locally
2. See wikimedia commons card component not properly aligned.

## Screenshots
![Screenshot 2022-11-05 122436](https://user-images.githubusercontent.com/103826657/200117520-a606120c-089c-418b-9150-b5e027a84f20.jpg)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by dikehprosper** [comment]
@possumbilities please triage this issue

**Comment by dikehprosper** [comment]
@possumbilities can I proceed with working on this??

**Comment by JennySimen** [comment]
@dikehprosper with the new structure of the engine buttons, that bug is no longer found.

**Comment by dikehprosper** [comment]
@JennySimen

**Comment by possumbilities** [comment]
Seems to be resolved by the work in #168

**Comment by NEGRAH-S** [comment]
Hey , wanted to settle this bug but can't find it anymore is that resolved?

**Comment by possumbilities** [comment]
@NEGRAH-S This was apparently resolved by a recent PR 
* #206

**Comment by possumbilities** [comment]
Adding @PreciousOritsedere here
