### ISSUE TITLE
[Feature] Improve footer links' readability

### ISSUE THREAD

**Issue by mbonamensa** [creativecommons/search#169]
## Problem

After new updates, the footer links look crowded and a little too bold. See screenshot:
![Screenshot (63)](https://user-images.githubusercontent.com/85899285/201472653-979b5783-cab6-4db2-89ff-c90f47d888cd.png)

## Description

This would remove the boldness and style links so it is consistent with the main cc website footer here: https://creativecommons.org/
Where the link is underlined and the color changes on hover. See screenshot:
![Screenshot (64)](https://user-images.githubusercontent.com/85899285/201472671-df916017-fe6a-4d2c-bd5d-51d1b79d3dec.png)

## Alternatives

An alternative will be to change the links' color or increase the `letter-spacing` which will be inconsistent with the main cc website.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by mbonamensa** [comment]
@possumbilities happy to work on this and hear your thoughts.

**Comment by dikehprosper** [comment]
@mbonamensa already worked on this dear

**Comment by mbonamensa** [comment]
@PreciousOritsedere happy to work with you on this when it's triaged by @possumbilities 
What are your thoughts on how to go about this?

**Comment by op-amateur** [comment]
Can you please assign me this issue. thank you.

**Comment by possumbilities** [comment]
This is blocked by active work. Moving to `blocked` for now. Once the `dev-refactor` branch is submitted it would correct this behavior.
