### ISSUE TITLE
[Feature] Refactor current CC search to correspond with Creative Commons Website

### ISSUE THREAD

**Issue by PreciousOritsedere** [creativecommons/search#172]
## Problem
The legacy CC meta search site doesn’t match the current visuals of the rest of CC web entities

## Description
This is a main issue that will connect and solve the sub-issues listed below:

- #60 
- #67 
- #129 
- #159 

## Implementation

- [x ] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
Resolved in new site merge: https://github.com/creativecommons/search/pull/206
