### ISSUE TITLE
[Feature] Create Semantic HTML <header> with new CSS styling that matches the new look and feel of Creative Commons' sites

### ISSUE THREAD

**Issue by possumbilities** [creativecommons/search#179]
This is a sub-issue of:
* #173 

## Problem
The `<header>` of the site does not conform to the new look and feel of the Creative Commons' sites. 

Furthermore, the HTML itself needs to be semantic and modern in its structure and element usage.

## Description
A new header needs to be created that follows the new look and feel, is semantic, and modern in its code structure. 

- Visual example to follow: [Creative Commons Open Source Blog](https://opensource.creativecommons.org) 
<img width="1089" alt="Screen Shot 2023-01-03 at 9 42 46 AM" src="https://user-images.githubusercontent.com/109087089/210391081-754c16bf-c924-4586-93d8-c01b5f1caf2c.png">

- An HTML code example to follow: https://github.com/creativecommons/creativecommons.org-prototype/blob/main/src/index.html (is at present incomplete, but working towards semantic structure, offers a starting place to build/consider from)

CSS styling will need to be written new, or incorporate styling from:[ creativecommons/vocabulary ](https://github.com/creativecommons/vocabulary/tree/main/dist/css)

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by PreciousOritsedere** [comment]
Thank you. I'll love to work on this

**Comment by Cronus1007** [comment]
@possumbilities Shall I take up this issue?

**Comment by possumbilities** [comment]
@Cronus1007 Hi! Thank you for your excitement, but I believe that @PreciousOritsedere is actively working on this still so I'd suggest you approach another Issue on one of the repositories ❤️
