### ISSUE TITLE
[Feature] Create Semantic HTML <body> with new CSS styling that matches the new look and feel of Creative Commons' sites

### ISSUE THREAD

**Issue by PreciousOritsedere** [creativecommons/search#182]
This is a sub-issue of:
- #173 

## Problem
The `body` of the site does not conform to the new look and feel of the Creative Commons' sites.

Furthermore, the HTML itself needs to be semantic and modern in its structure and element usage. There is also the need for  modern CSS styling.

## Description
A new body needs to be created that follows the new look and feel, is semantic, and modern in its code structure.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by op-amateur** [comment]
Please assign me this issue. Thank you.
