### ISSUE TITLE
[Bug] The `docker-compose.yml` mount directory is incorrect

### ISSUE THREAD

**Issue by possumbilities** [creativecommons/search#211]
## Description
Previously the site was a GitHub pages site that built into `/docs` and now its just flat static html site hosted on Netlify, and builds into `/src` as such, the `docker-compose.yml` file mounts to the wrong directory. 

## Reproduction

1. run: `docker compose up`
2. See `Index of/` instead of site

## Expectation
Docker should mount the `/src` directory instead.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by krysal** [comment]
@possumbilities Looks like this was fixed in #212.

**Comment by possumbilities** [comment]
@krysal Good spot! Thankyou! ❤️
