### ISSUE TITLE
[Bug] Site throws a 404 for the `library-vars.css` file referenced in the `style.css` file

### ISSUE THREAD

**Issue by possumbilities** [creativecommons/search#213]
## Description
The reference to the `library-vars.css` file in the top of the `style.css` file is looking in the wrong directory. 

It is looking for `css/vocabulary/library-vars.css`

when it should be looking for `vocabulary/library-vars.css`

## Reproduction

1. Visit search.creativecommons.org
2. Open the dev console
3. See error: `Failed to load resource: the server responded with a status of 404 ()    library-vars.css:1`

## Expectation
This 404 should not occur, the file should load into the `style.css` file with the correct path reference.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by ImaJin14** [comment]
Hi @possumbilities, I just tried to reproduce the error but everything is working fine from my end...
