### ISSUE TITLE
[Bug] Search Input and Button have spacing that should not be present

### ISSUE THREAD

**Issue by possumbilities** [creativecommons/search#235]
## Description
The search input area, and the search button have spacing between them that should not be there.

## Reproduction

1. Load page
4. See error.

## Expectation
The input box and search button should be flush to each other.

## Screenshots

<img width="699" alt="Screen Shot 2024-10-03 at 2 08 15 PM" src="https://github.com/user-attachments/assets/db625f21-e0b1-4236-a3ba-c300198ee9e9">

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by Mariam-Senzia** [comment]
Hi @possumbilities,

I’ve created a pull request #243  to address issue #235. The changes include:

- Removed the flex gap in the .body-search container.
- Adjusted the spacing between the heading, input, and search button.

Please review the PR when you have a chance. Thank you!
