### ISSUE TITLE
[Bug] An empty Menu Button in the Mobile screens 

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/search#237]
## Description
When you switch to mobile screen, a menu button appears. This menu has no content and hence should be removed.

## Expectation
There should be no Menu button since there are no contents. Also, in the desktop screens, there are no menus(there is no navbar).
- [x ] I would be interested in resolving this bug.

**Comment by Queen-codes** [comment]
Hi! I'm leaving this comment here as suggested so this issue can be officially assigned to me. Thank you @possumbilities
