### ISSUE TITLE
[Feature] the primary menu as well as button in ancilliary-menu is missing

### ISSUE THREAD

**Issue by Sophiek9h** [creativecommons/search#245]
##Problem
Disparities in design of the header in search portal and Vocabulary 

## Description
the **primary-menu** that consists of  "about, contact, blog, support" as well a button in ancilliary-menu is missing in the search portal 

## Implementation
The nav class should be collected from vocabulary and used in the search portal 

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
Hi and thanks for this contribution! 

This is a duplicate of an already closed issue #237. Please verify a Issue doesn't already exist before creating a new one.

Please see the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/)

Closing as duplicate.

**Comment by Sophiek9h** [comment]
Oh
Thanks for the feedback
