### ISSUE TITLE
[Bug] No cursor-pointer feature in the search button

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/search#260]
## Description
Currently, when a user hovers over the search button, nothing shows that it can be clicked. The default cursor just appears.
This lacks UX.

## Reproduction

1. Add a cursor pointer to the button to enhance UX

## Expectation
When a user hovers or places his or her cursor on the button, there should be a pointer instead of the default arrow cursor.
- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
Hi @SisiVero I see you've already listed a number of Issues as being interested in resolving them. Please allow other contributors to also submit PRs against Issues as well.
