### ISSUE TITLE
[Feature] Universal Heading Style Causes Unintended Design Disparity in Footer

### ISSUE THREAD

**Issue by Sophiek9h** [creativecommons/search#272]
## Problem
In the Vocabulary.css, there is a universal style applied to every h2 and h3 element that transforms the text to uppercase. This style affects the headings in the footer, which is inconsistent with the intended design. The line of code responsible for this style does not exist in the Vocabulary repository but is applied globally, leading to unintended design consequences.

## Description
The current global text-transform: uppercase; style for all h2 and h3 elements modifies the headings in the footer. The expected behavior is that headings in the footer should not be automatically transformed to uppercase, allowing for more flexibility in design. Removing this universal style or applying a more specific style will ensure that only the intended headings are affected.

## Alternatives
1. Remove Universal Style: Remove the universal text-transform: uppercase; style from h2 and h3 elements in the global CSS. This would restore the intended design for headings, particularly in the footer.

2. Scoped Styling: Instead of applying a global style, restrict the uppercase transformation to specific headings in defined components (e.g., sections where uppercase is necessary).

## Implementation
- [x ] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
The styling follows the intended use of a cascade in CSS, applying broad styles across elements that are then specifically modified or overridden contextually as necessary.

Closing, as not within the intended scope of the project.
