### ISSUE TITLE
[Bug] Search Button: Default Button Border Not Removed Across All Screen Sizes

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/search#304]
## Description

The default border of the button was not removed for all screen sizes. The border is still visible on both desktop and mobile screens. It's essential to remove the default button border to maintain design consistency across the interface and avoid a cluttered or outdated appearance, especially when custom button styles are applied. And since the button has a background color, a border is not needed.

## Reproduction

1. Access the interface on a desktop or large screen device.
2. Observe that the button still has the default border.
3. Switch to a mobile device or use developer tools to simulate a mobile screen size.
4. Note that the button's default border is still visible.
5. See error.

## Expectation

The button’s default border should be removed consistently on all screen sizes to ensure a clean and modern appearance
## Screenshots

Desktop screen with default: 
<img width="301" alt="defaultBorderPresent" src="https://github.com/user-attachments/assets/75b1c5af-dc05-475a-a343-067ac0950a92">

Desktop screen without default border:
<img width="281" alt="noDefaultBorder" src="https://github.com/user-attachments/assets/2885d550-09d2-4450-981a-dd83da427874">

Mobile screen with default border: 
<img width="266" alt="mobileViewWithBorder" src="https://github.com/user-attachments/assets/952e9cb3-d8c3-48d3-b1e0-5c622fd3ad5b">

Mobile screen without default border:
<img width="272" alt="mobileViewNoBorder" src="https://github.com/user-attachments/assets/aace4412-7582-466f-9e01-6fd5a9dbc469">

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by LavellTheDev** [comment]
@SisiVero @possumbilities Is this task currently being worked on? Or is it in the process of being resolved?
