### ISSUE TITLE
[Feature] Improve Mobile Layout by Displaying Search Engine Cards in a Two-Column Grid

### ISSUE THREAD

**Issue by SylviaUzoh1** [creativecommons/search#310]
## Problem

On the Creative Commons search page (https://search.creativecommons.org/), the selectable search engine cards span the full width of the mobile screen, which makes the list longer and requires more scrolling. This layout can result in a suboptimal user experience, as users may need to scroll extensively to view and select from all available search options.

## Description

To enhance the user experience on mobile devices, I propose adjusting the layout of the selectable search engine cards to display in a two-column grid on mobile screens. This will reduce the vertical length of the list, allowing users to view more search engine options at once, minimizing the need for excessive scrolling.

## Alternatives

An alternative solution would be to make the cards smaller, or implement a horizontal scroll layout for the cards on mobile devices. However, displaying the cards in a two-column grid would keep the interaction simple and intuitive, while reducing the list’s length.

## Additional context

A two-column grid layout for mobile screens would maintain consistency with common mobile UI patterns, making the interface more user-friendly and visually appealing.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
They are already displayed in two columns on mobile. However, what might be helpful is extended the width within which they stay two columns so that they don't break to one column until the screen becomes much narrower.

**Comment by SumaiyaaRq** [comment]
@possumbilities I've submitted a PR for resolving this issue.
