### ISSUE TITLE
[Feature] README.md file update

### ISSUE THREAD

**Issue by ImaJin14** [creativecommons/search#49]
## Problem
README.md 

## Description
README.md file does not contain the steps required to setup the project locally on a personal work environment 

## Alternatives
This will help new contributors to be able to setup their environment with ease... This is especially for those who are new to open source 

## Additional context
Links to various sites that could help the contributor during setup phase

## Implementation

- [ x] I would be interested in implementing this feature.

**Comment by Biki-das** [comment]
Already raised #45, and i am working on this, you can look up to other issues.

**Comment by ImaJin14** [comment]
@Biki-das okay thanks for the heads up
