### ISSUE TITLE
[Change] Rename project to CC Search Portal, all text occurrences

### ISSUE THREAD

**Issue by possumbilities** [creativecommons/search#54]
## Description
The project known as CC Search, CC Meta Search, Old Search, and Legacy CC Search needs all text occurrences to be changed to the new title: `CC Search Portal`.

Additionally, the wording `oldsearch.creativecommons.org` in the footer, needs to be changed to `CC Search Portal`

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by ImaJin14** [comment]
Hi I'll like to work on this issue @possumbilities

**Comment by brendamoreira** [comment]
Hi, I'm Brenda, from outreachy. If this issue is not taken, can I work on this one?

**Comment by kuicpet** [comment]
Hi, I'm Kingsley, an Outreachy applicant, I love contributing to this project, can we create issues based on the WAVE accessibility report on the https://oldsearch.creativecommons.org/ website

**Comment by MrOrero** [comment]
Hi, I'm Orero, an Outreachy applicant, I would love to contribute to this project by working on this issue

**Comment by Nuel-Eneji** [comment]
Hello, I'm Nuel From outreachy. I'd want to work on this topic if it's not already taken. Thanks

**Comment by ImaJin14** [comment]
@Nuel-Eneji please I'm working on this issue already

**Comment by albinazs** [comment]
Hello @possumbilities! I'm an Outreachy applicant and I would love to work on this issue!

**Comment by ImaJin14** [comment]
This issue has already been worked on and I have and active PR on it

**Comment by Jolah1** [comment]
Hello i'm jolade, an outreachy applicant, I will like to start working on this issue.
Thank You.

**Comment by codeinvoke7** [comment]
I'm an outreachy applicant and I would like to work on this issue

**Comment by possumbilities** [comment]
> Hi, I'm Kingsley, an Outreachy applicant, I love contributing to this project, can we create issues based on the WAVE accessibility report on the https://oldsearch.creativecommons.org/ website

Yes you can, that's a great approach to generate Accessibility specific Issues here on the repository
