### ISSUE TITLE
[Feature] Redesign Footer component

### ISSUE THREAD

**Issue by osujipius** [creativecommons/search#60]
## Problem
The current footer is really bad visually and does not meet the current standards of other UI/UX trend 

## Description
This feature will make the Footer more pleasing to look at and more accessible

## Additional context
For me personally as a Frontend Developer the current Footer is way below standard with the ever evolving world of UI/UX
The overall goal for the new footer is to put it in alignment with the current universal footer found on newer Creative Commons sites. See an example here: https://opensource.creativecommons.org/

![Screenshot (161)](https://user-images.githubusercontent.com/94569961/195169318-b75a6c10-6eb1-480b-af26-3c8812c07336.png)

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Tammy-Ajoko** [comment]
Hi, I'ld like to work on this issue

**Comment by JennySimen** [comment]
Hi @OsujiPius I will like to work on this issue

**Comment by OsujiPius** [comment]
@JennySimen Already working on it

**Comment by Straw4yu** [comment]
@possumbilities I'll like to work on this project.

**Comment by possumbilities** [comment]
@OsujiPius thanks for adding more clarification, and I appreciate your enthusiasm! 

I agree the footer needs to be updated, as does a lot of the visual aesthetic of the site. The overall goal for the new footer should be to put it in alignment with the current universal footer found on newer Creative Commons sites. See an example here: https://opensource.creativecommons.org/

That's definitely inline with the direction you were already headed.

**Comment by OsujiPius** [comment]
@possumbilities thank you. I will get to work right away

**Comment by possumbilities** [comment]
@OsujiPius can you update the original issue to expand a bit with this information about following the other universal footers?

**Comment by OsujiPius** [comment]
> @OsujiPius can you update the original issue to expand a bit with this information about following the other universal footers?

Sure I can do that

**Comment by PreciousOritsedere** [comment]
Hi @OsujiPius are you still working on this? Or can I get on it? 😊

**Comment by OsujiPius** [comment]
Hey @PreciousOritsedere I am on it

**Comment by possumbilities** [comment]
Resolved in new site merge: https://github.com/creativecommons/search/pull/206
