### ISSUE TITLE
[Bug] Cleanup Codebase CSS files tab and spacing formatting

### ISSUE THREAD

**Issue by OsujiPius** [creativecommons/search#65]
## Description
The codebase currently has a lot of duplicates of code and files that do not seem necessary. There is also a lot of generic errors especially in the CSS files which can cause a lot of confusion especially to people new to the codebase.

## Reproduction
1. Open `ie8-and-down.css`
2. Open `primary.styles.css`
3. Open `style.css`

## Expectation
1. Fix all errors in the CSS files 
2. Remove all unused code

##Additional Context
The errors in the CSS range from wrong `Syntax` and No opening curly brace in one instance

## Screenshots

![Screenshot (162)](https://user-images.githubusercontent.com/94569961/195308668-626014d0-9a07-48ac-a4d3-173d53e7698e.png)
![Screenshot (163)](https://user-images.githubusercontent.com/94569961/195308688-5b64808a-f98c-4b20-9b4a-09a96b87cde0.png)
![Screenshot (164)](https://user-images.githubusercontent.com/94569961/195308709-5fac4f13-fbd1-4ad4-bb5b-c235a50e40ac.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by OsujiPius** [comment]
@possumbilities I think it would make sense if I also do this

**Comment by possumbilities** [comment]
@OsujiPius Thanks for outlining another Issue, but let's try to leave this one open for others to do if it gets into a status of "status: ready for work" so others have a chance to contribute as well. :)

**Comment by RealRichi3** [comment]
@possumbilities  i would like to take this issue

**Comment by possumbilities** [comment]
@OsujiPius could you add more details about the specific errors you've encountered here?

**Comment by OsujiPius** [comment]
@possumbilities Yes I can. 🙂

**Comment by PreciousOritsedere** [comment]
I would like to work on this issue

**Comment by OsujiPius** [comment]
@possumbilities I have updated the description a little bit

**Comment by PreciousOritsedere** [comment]
@OsujiPius Thanks, I'm currently working on this :)

**Comment by AbeerTannous** [comment]
I see this issue still open can I work on it or it been taken ?

**Comment by PreciousOritsedere** [comment]
Hi @AbeerTannous I have worked on this issue, just waiting for the status to change so I can create a PR

**Comment by AbeerTannous** [comment]
sounds good , thanks

**Comment by ImaJin14** [comment]
> Hi @AbeerTannous I have worked on this issue, just waiting for the status to change so I can create a PR 

Open a PR... It'll change the status when it's under review
