### ISSUE TITLE
Updating the website UI

### ISSUE THREAD

**Issue by MariamOsman11** [creativecommons/search#66]
I want  redesign the existing "creativecommons" components into the current standard. I discovered it's necessary to set appealing background color , and use CSS custom property to remove redundency. Also, animate some buttons.

I'm doing that to provide clean design and responsiveness also the user to enjoy exploring the "creativecommon" website

**Comment by MariamOsman11** [comment]
@possumbilities can I kindly contribute by improving the appearance of creativecommons

**Comment by possumbilities** [comment]
@MariamOsman11 Hi! and thank you for your excitement! ❤️ 

* Can you please return the Issue template and fill that out, rather than deleting it. It's ok to modify some of it as necessary. 
* Can you also provide more details about what specifically this Issue is about, the reasoning behind, etc. and any specific approach you would hope to take in resolving it. (if relevant)

**Comment by MariamOsman11** [comment]
@possumbilities  kindly review the issue I update. 
appreciated!

**Comment by ImaJin14** [comment]
> @possumbilities kindly review the issue I update. appreciated!

@MariamOsman11 your PR can't be reviewed because it's not well explained nor linked to any issue.... Please refer to contribution.md on how to contribute to this open source project thanks

**Comment by MariamOsman11** [comment]
@ImaJin14  kindly elabrote more. do you see the issue I raised?I'm confused here! time is moving so fast. I have never contributed to open source. write the hierachy of the work required here you seem to understand it. Appreciated

**Comment by ImaJin14** [comment]
The pr you asked to be reviewed I.e #62 isn't linked to any issue and hence can't be reviewed... PS : this current issue is good and you can submit a PR for it which will be very much appreciated

**Comment by MariamOsman11** [comment]
@ImaJin14  thank you so much for your help. I understood now. will work on it.

**Comment by possumbilities** [comment]
This is a rather large issue in scope, and I think it would be best to split this off into different areas or pages, and there are already a few Issues that are setup to do that.

For example: 
* #60
* #67 
* #70
* #74
