### ISSUE TITLE
[Feature] use cc global components to customize site appearrance

### ISSUE THREAD

**Issue by ImaJin14** [creativecommons/search#74]
## Problem

code base doesn't make use of cc global components elements such as footer, header and explorer which will simplify project code base 

## Description

CC global components provides already customized elements which could be used all over any cc site hence reducing lines of code and making page easily debug-able 
## Alternatives

could allow site to use alternative components which will make code base more stressful to debug
## Additional context

css files for the above could be cleared and modified to use that of cc global components
## Implementation

- [x] I would be interested in implementing this feature.

**Comment by ImaJin14** [comment]
@possumbilities i think this is a great way to improve on the site if you approve for the above changes to be made will help as insight to issues #67 and #60 !!!

**Comment by ImaJin14** [comment]
@possumbilities the cc global components includes the cc footer... Cc header and cc explorer which if embedded into the search site will go a long way to remove all css styles related to this the already existing footer and header making the UI better with fewer lines of code

**Comment by ImaJin14** [comment]
This will also reduce bugs

**Comment by Rubadel** [comment]
@ImaJin14  I am  interested in implementing this Task with you , as I have some designing for make it better ..

**Comment by Jolzyfx** [comment]
@TimidRobot please i would love to be assigned this project , using the cc global components in changing the site appearance will be superb, Can't wait to work on the project . Thanks

**Comment by possumbilities** [comment]
Resolved in new site merge: https://github.com/creativecommons/search/pull/206
