### ISSUE TITLE
[Bug] <Removing line inconsistency and correcting tab spacing in style.css>

### ISSUE THREAD

**Issue by AnnyTheExplorer** [creativecommons/search#76]
## Description

I will like to remove line inconsistency and correct tab spacing in style.css

## Reproduction
1. open cc search in editor.
1. navigate to style.css file.
1. check lines 9, 15, 23...
1. see error.

## Expectation

The line spacing in 
> style.css file should be consistent so that the code will be more organized.
> tab spacing should be corrected as well.

## Screenshots

![1st Report](https://user-images.githubusercontent.com/109468437/195391030-d97d5cc5-a6f5-4303-b185-a9f6fe4fe8a9.JPG)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by AnnyTheExplorer** [comment]
#76 Removing line inconsistency in style.css 
@TimidRobot @possumbilities 

I will like to work on this issue.

**Comment by possumbilities** [comment]
@AnnyTheExplorer can you also outline that the tab spacing needs correcting in the Issue?

**Comment by AnnyTheExplorer** [comment]
> 

Absolutely

**Comment by AnnyTheExplorer** [comment]
Do I have permission to work on the issue?
@possumbilities

**Comment by possumbilities** [comment]
@AnnyTheExplorer sure, please do. ❤️

**Comment by AnnyTheExplorer** [comment]
Thank you!
#76 Done
