### ISSUE TITLE
[Feature] Improve on site contrast

### ISSUE THREAD

**Issue by Njong392** [creativecommons/search#78]
## Problem
Ran the site through an accessibility checker, and there seem to be some contrast issues. Especially with the white text over the greeny-background. The contrast ratio currently stands at 3.14.

## Description
People with low contrast sensitivity will have issues reading the white text on the green background. The green shade could be altered and made a little darker.
![Shot of site colors with low contrast background](https://user-images.githubusercontent.com/81039882/195412578-cad9ccc0-f6c9-48bf-93b8-c93cd0c8ae73.png)

Adding a background color like #28480F will take the contrast up to 10.38. 
![Shot of site colors with improved green shade](https://user-images.githubusercontent.com/81039882/195412606-185da24c-c50f-4cb8-92ea-e0481fba899f.png)

## Alternatives
A shade which is only slightly greener than the current one could also work.

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
This entire project needs to be brought up to the current design standards on newer site, BUT that's not likely to happen overnight and I could see the argument that we should possibly resolve this in the short-term.

**Comment by Njong392** [comment]
> This entire project needs to be brought up to the current design standards on newer site, BUT that's not likely to happen overnight and I could see the argument that we should possibly resolve this in the short-term.

Amazing. Could I be assigned to this? I'll get working on it.

**Comment by Marvisjaja** [comment]
> This entire project needs to be brought up to the current design standards on newer sites, BUT that's not likely to happen overnight and I could see the argument that we should possibly resolve this in the short-term.

please where is the link to the entire project? some slight arrangements are required

**Comment by possumbilities** [comment]
@Marvisjaja the entire project I'm referring to is the codebase these Issues are attached to. https://github.com/creativecommons/search/

**Comment by Njong392** [comment]
Hey @possumbilities sorry if I am taking forever on this, but I am having issues with docker. The README says to install docker, but then `docker compose up` won't work without installing `docker compose` Even after that, `docker compose up` still says `'compose' is not a docker command.`

![Screenshot from 2022-10-13 20-41-36](https://user-images.githubusercontent.com/81039882/195694143-77247a0c-8643-4fa7-be01-1c678c396109.png)

**Comment by possumbilities** [comment]
@Njong392 Since this is a little off topic would you mind moving this to the community slack `#cc-dev-workprograms` channel? I'd suggest asking the same question there, and providing operating system, and version details along with this screenshot. Hopefully myself or someone else in the community will have a solid answer to help :)

**Comment by Marvisjaja** [comment]
Am a new comer . And I seem lost . Don’t know how to contribute etc . 


Sent from Yahoo Mail for iPhone


On Thursday, October 13, 2022, 7:46 PM, possumbilities ***@***.***> wrote:




@Marvisjaja the entire project I'm referring to is the codebase these Issues are attached to. https://github.com/creativecommons/search/

**Comment by possumbilities** [comment]
@Marvisjaja I'm glad you want to contribute, but the better place to ask this is likely the [Community Slack](https://opensource.creativecommons.org/community/#slack), if you haven't already. If you ask there you should be able to get a lot of answers from community members about Contributing. :)

**Comment by VictoriaAjala** [comment]
Hello @possumbilities It seems @Njong392 is having issues with this, can i possibly work on this? I would be glad to help.

**Comment by ImaJin14** [comment]
> Hello @possumbilities It seems @Njong392 is having issues with this, can i possibly work on this? I would be glad to help.

@Njong392 is working on it... She just has a measure setback with configuring her local work station which I'm sure should be done by today....

Please wait if by tomorrow she hasn't made and effort you can then work on it:)

**Comment by Marvisjaja** [comment]
Thank you for replying pls can I get the slack url so I can join the community 


Sent from Yahoo Mail for iPhone


On Thursday, October 13, 2022, 9:57 PM, possumbilities ***@***.***> wrote:




@Marvisjaja I'm glad you want to contribute, but the better place to ask this is likely the Community Slack, if you haven't already. If you ask there you should be able to get a lot of answers from community members about Contributing. :)

**Comment by possumbilities** [comment]
@Marvisjaja Sure, the link is here in the original comment I left earlier:

> @Marvisjaja I'm glad you want to contribute, but the better place to ask this is likely the [Community Slack](https://opensource.creativecommons.org/community/#slack), if you haven't already. If you ask there you should be able to get a lot of answers from community members about Contributing. :)

**Comment by Marvisjaja** [comment]
Okay . I opened an issue that I would love to work on. But no reply yet . Can you help me with that ? I want to work on the responsiveness 


Sent from Yahoo Mail for iPhone


On Friday, October 14, 2022, 2:40 PM, possumbilities ***@***.***> wrote:




@Marvisjaja Sure, the link is here in the original comment I left earlier:


@Marvisjaja I'm glad you want to contribute, but the better place to ask this is likely the Community Slack, if you haven't already. If you ask there you should be able to get a lot of answers from community members about Contributing. :)

**Comment by possumbilities** [comment]
@Marvisjaja Thanks for contributing, but please move this conversation to the Community Slack or the related Issue, so we don't clutter up this Issue which is not related to your help :)

**Comment by dikehprosper** [comment]
@possumbilities .....@Njong392 has not submitted a PR  and it's been more than 7 days as stated in the contribution guidelines...
I would be glad if given permission to work on this

**Comment by dikehprosper** [comment]
Working on this
