### ISSUE TITLE
[Bug] Wrong Spelling(Typing Error)

### ISSUE THREAD

**Issue by FrancoFrancis** [creativecommons/search#79]
This PR   #71  by me fixes this issue

## Description
buttons typed  as **btutons** instead of **buttons** in `search.js`  file line 15.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by ImaJin14** [comment]
Conflicting with #75 but no big deals one will be closed!!!

**Comment by FrancoFrancis** [comment]
I am so sorry I am creating an issue after opening a pr, according to the guidelines I am supposed to open one before creating a PR.

**Comment by FrancoFrancis** [comment]
> Conflicting with #75 but no big deals one will be closed!!!

Thank you bro.

**Comment by possumbilities** [comment]
duplicate of #75
