### ISSUE TITLE
[] Incomplete code no how to run docker on the ReadMe 

### ISSUE THREAD

**Issue by mildrette** [creativecommons/search#80]
when I was following the code to run Docker in the section (DOCKER COMPOSE UP) as the code set it did not work for me.

## Reproduction

1. open the terminal in my code editor
3. run code docker compose up

## Screenshots
/home/zoe/Pictures
![firstdockererror](https://user-images.githubusercontent.com/99267408/195427147-821b8116-b74c-4709-9333-5f469c4f80b8.png)

## the fixed result
* it took a while to figure out Sudo has to go in front before Docker compose up.
![dockerFinalresult](https://user-images.githubusercontent.com/99267408/195427226-2ab6a9b3-1575-411e-9961-4d50b1d78dce.png)

## Resolution

- [x ] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
@mildrette can you list out in the Issue what operating system and version you are running this on?

**Comment by mildrette** [comment]
okay

> @mildrette can you list out in the Issue what operating system and version you are running this on?

okay I am running Ubuntu 22.04.1 LTS

**Comment by ImaJin14** [comment]
Okay on your Linux system your not the root user and docker was installed as a component of the root user hence the need for sudo each time you wish to run the docker container


The readme.md file doesn't need sudo as it is a general setup configuration file for users of various systems

**Comment by ImaJin14** [comment]
![Screenshot_20221012-204254.png](https://user-images.githubusercontent.com/112979436/195433603-48891576-9e1a-4b69-bd29-ac736c4c619c.png)

There's how to run docker without use of the sudo command !!!

**Comment by mildrette** [comment]
> Okay on your Linux system your not the root user and docker was installed as a component of the root user hence the need for sudo each time you wish to run the docker container
> 
> The readme.md file doesn't need sudo as it is a general setup configuration file for users of various systems

understood thank you very much

**Comment by possumbilities** [comment]
Thank you for hoping this! But I'm closing this since there's a way to resolve this otherwise from the user-end, as explained above by @ImaJin14

**Comment by mildrette** [comment]
> Thank you for hoping this! But I'm closing this since there's a way to resolve this otherwise from the user-end, as explained above by @ImaJin14

okay
