### ISSUE TITLE
[Bug] <Improve readability by correcting tab inconsistencies in home-buckets.php>

### ISSUE THREAD

**Issue by mbonamensa** [creativecommons/search#84]
## Description
 The tab inconsistencies and spacing make the code difficult to read even with the comments indicating closing tags.

## Reproduction

1. Open cc search in the editor
2. Navigate to cc-wp/home-buckets.php 
3. Check lines 3-5, 74-108 
4. See error.

## Expectation
I expected to see indexing in the code that would make it a bit more readable 

## Screenshots
![Screenshot (38)](https://user-images.githubusercontent.com/85899285/195569502-fe2cbaa3-0fb8-4817-80ae-86ba736a08c6.png)

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by mbonamensa** [comment]
@possumbilities can you please assign me to do this? I'd love to start work on it.

**Comment by possumbilities** [comment]
After further research, I don't believe this file is used in a visible way anymore (if it ever was). So I'm closing this Issue since these changes won't be necessary.

Thank you for pointing it out none-the-less! ❤️

**Comment by mbonamensa** [comment]
> After further research, I don't believe this file is used in a visible way anymore (if it ever was). So I'm closing this Issue since these changes won't be necessary.
> 
> Thank you for pointing it out none-the-less! ❤️

Alright, thanks for letting me know ❤️
