### ISSUE TITLE
[Feature] Redesign the input Component

### ISSUE THREAD

**Issue by dikehprosper** [creativecommons/search#85]
## Problem
The current  input component is not attractive visually and also does not meet the standard of design.

## Description
This feature will make the section more attractive and open to all

## Additional context
As an experienced Front-end developer, the input section does not meet a good standard and needs to be worked-on. The results would make an attractive and good-looking input section that will be open to all.

## Implementation

- [x] I would be interested in implementing this feature.
![redesigned](https://user-images.githubusercontent.com/103826657/195578164-b14c5dfc-bfca-4ba1-9ff1-e15632527593.jpg)

**Comment by dikehprosper** [comment]
@possumbilities @TimidRobot I would love to work on this

**Comment by mbonamensa** [comment]
This looks good @dikehprosper and I agree the design needs improvement. I think the whole site can look better. 
@possumbilities is there a design document that is standard for the website?

**Comment by possumbilities** [comment]
@dikehprosper Thank you for pointing this out, and for this contribution! (submitting an issue, even if it doesn't move to a status that can be worked on immediately, is still a contribution, and we're grateful for it)

I agree with you that this is something that needs to be addressed but at the moment there isn't a clear path for handling a search input on the newer design (see https://opensource.creativecommons.org/, and specifically the footer which has the only example of an input field). I'll need to do further research before we move forward with addressing this on how best we'd align this with the newer design direction everything is taking.

In general, most new features are going to take more deliberation and research before they get to a status  of "ready to work", whereas bug fixes are less likely to need as much thought.

**Comment by dikehprosper** [comment]
@possumbilities alright ma

**Comment by possumbilities** [comment]
Resolved in new site merge: https://github.com/creativecommons/search/pull/206
