### ISSUE TITLE
[Feature] Creating a pop-up message for countries whose laws do not affect the rights of creators and authors

### ISSUE THREAD

**Issue by JeffyDave** [creativecommons/search#86]
### Problem
Countries on the CC Rights Back Resource Page that their laws do not affect the rights of the author or creator have no specific action on the map even when being clicked.

### Description
We can change this by adding the dbclick feature in JS which shows the message to the users that the country they are currently in does not affect their rights as the author or creator on their creative works. This way the user does not get confused when checking for their country.

### Implementation
- [x] I would be interested in implementing this feature.

**Comment by JeffyDave** [comment]
@possumbilities @TimidRobot I would love to work on this. Could you please triage this issue?

**Comment by possumbilities** [comment]
@JeffyDave Thankyou for taking the time to contribute! What page of the CC Search Portal are you referring to?

**Comment by JeffyDave** [comment]
This page https://rights-back-beta.creativecommons.org/
I went through it and I thought it would make a better experience for users

**Comment by JeffyDave** [comment]
![Screen Shot 2022-10-13 at 3 48 42 PM](https://user-images.githubusercontent.com/106249556/195630905-7ce7d59a-49a0-4e20-9408-43f981b07385.png)

This is the picture of the map I'd love to work on.

**Comment by possumbilities** [comment]
@JeffyDave Ah, I see. While I appreciate your desire to improve the UX, this page is not related to this project (CC Search Portal)

The site you've linked is for this project: https://github.com/creativecommons/reversionary-rights I'd suggest you go there, read through the Issues present (if any), and go from there with any further contributions. :)

**Comment by JeffyDave** [comment]
Okay, thank you very much
