### ISSUE TITLE
[Bug]  Js error `j.handler.apply is not a function` showing in the console locally

### ISSUE THREAD

**Issue by JennySimen** [creativecommons/search#90]
## Description
After running the project, there is an error in the console `Uncaught TypeError: j.handler.apply is not a function`. This error does not seem to affect the platform so far but it needs to be fixed. 

Upon investigation, the error comes from `script.js` file on line **114** where we are displaying a carousel. On the instance where the carousel is not displayed, this causes the error in the console.

## Reproduction

1. Run the project locally
2. Inspect the home page
3. Go to the console tab
4. See error.

## Expectation

The platform should run without any JS error in the console.

## Screenshots

<img width="1890" alt="Screen Shot 2022-10-14 at 10 23 14" src="https://user-images.githubusercontent.com/44881714/195812270-f425e59b-dd72-4027-9d72-8ce48a7efa34.png">

## Environment

- Browser: (Chrome, Safari; Firefox)

## Additional context

On the current version of the platform, the carousel is not displayed but the component is found in the codebase. This error might not be experienced by others who have the carousel displayed but it would be good to have a solution which would not show an error in both cases.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by JennySimen** [comment]
@possumbilities could I be assigned to this, I'll love to work on it

**Comment by Rubadel** [comment]
Could I work On this task ? I am excited to do if it is still available

**Comment by JennySimen** [comment]
@Rubadel I already work on it and created a PR
