### ISSUE TITLE
[Feature] Improving the legibility of the site content to enhance readibility

### ISSUE THREAD

**Issue by pragmaticAweds** [creativecommons/search#91]
## Problem
Website content should be legible to increase readability in the user experience. This is an important aspect that also contributes to users staying or leaving the website.

I checked the website, and the first thing that caught my attention was the font size which was too small. This can prevent users with/without eye problems to read the content of the website. 

## Description

This is an image with the current font size which I think is not ideal.

<img width="1053" alt="Screenshot 2022-10-14 at 9 51 06 AM" src="https://user-images.githubusercontent.com/70960505/195807693-4ca1f14b-032c-4a99-8d87-9acd514b68c3.png">

My suggestion is to increase the font size to 14px or 16px for paragraphs and for titles it can be 16px with font-weight of 500.

## Alternatives
I also believe that using Arial or Roboto font family can improve the user experience.

## Implementation
 The implementation is quite simple:
- the paragraph font size can be increased to 14px.
- the title can be increased to 16px with a font weight of 500.

- [x] I would be interested in implementing this feature.

**Comment by pragmaticAweds** [comment]
Hi @possumbilities @TimidRobot Please can you triage this? I would love to start working on it.

**Comment by Jolzyfx** [comment]
hello @possumbilities @TimidRobot i would love to collaborate with you on this project . please assign it to me. Thanks

**Comment by possumbilities** [comment]
Increasing the typeface is reasonable, but I don't think we should be changing out the typeface/font used as a part of this. That's definitely something to do later with an aesthetic refactor, but well outside the scope of where things are at now.

**Comment by mbonamensa** [comment]
@pragmaticAweds have you started work on this?

**Comment by dikehprosper** [comment]
@possumbilities ..... @pragmaticAweds  has not submitted a PR and it's been more than 7 days as stated in the contribution guidelines...
I can help out on this if given permission to

**Comment by dikehprosper** [comment]
Working on this
