### ISSUE TITLE
[Feature] Add Thingiverse as an External Source

### ISSUE THREAD

**Issue by dullbenz** [creativecommons/search#94]
## Problem
The goal is to add a good number of external sources to give users a variety of results from different sources. 

## Description
In particular, [Thingiverse](https://www.thingiverse.com/) is one such external source with free 3D design models that can be downloaded and used.
Adding Thingiverse as an external source to CC search will be a good addition and will benefit our users.

![image](https://user-images.githubusercontent.com/40190640/195940860-41f8f82d-1187-4adf-b0ed-efcbd8f6e289.png)

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by dullbenz** [comment]
What caption text should we use to describe the content for Thingiverse. The site contains various 3D model designs.
Was thinking of using "**Image**" or "**MODEL_3D**" or "**3D Model**"

**Comment by PreciousOritsedere** [comment]
3D models sounds good

**Comment by dikehprosper** [comment]
“3D Model” is okay

**Comment by dullbenz** [comment]
#### I've run into a little issue with this task.
In effect, the problem is that in order to  apply the _"commercial purposes"_ and _"modify, adapt ..."_ filters as indicated by the checkboxes in the picture below, I browsed the [Thingiverse](https://www.thingiverse.com/) site and discovered that applying the _"customizable"_ filter corresponds to _"modify, adapt, ... "_ for CC search.

![image](https://user-images.githubusercontent.com/40190640/196000678-6352962f-ec36-49e0-8b30-b6dbe73a280a.png)

The problem is that, in order to implement _"commercial purposes"_ filter for CC search, I thought about leveraging the license filters on Thingiverse, but selecting any of the licenses simply displays _"NO Results"_ yet I actually verified and could see that there are items with these licenses.

**Comment by dullbenz** [comment]
I used the search param __"&license=cc"__ (which on Thingiverse stands for the CC Attribution Licence) as the equivalent to the _"use for commercial purposes"_ filter on __"CC search"__.
