### ISSUE TITLE
[Bug] the `selected` card on load functionality does not always have a card selected by default

### ISSUE THREAD

**Issue by JennySimen** [creativecommons/search#97]
## Description

When you run the project, a card is selected by default. There is a usecase where no card is selected when the page loads. 
This is caused by the fact that the card is randomly selected on load. The functionality for generating the randomly selected card uses the length of the engines to get a number as shown below:

`engine = engines[Math.floor(Math.random() * engines.length)];`

Since js arrays are zero indexed, the number generated from the function above will be in the range [0 - 10] which is 11 search engines instead of [0 - 9] which is 10 search engines.This will provide a usecase where no card is selected on page load because the randomly generated numer is `10` but there are only 0 - 9 search engines

## Reproduction

1. Run the project locally
2. Reload the project till you find a usecase with no selected card
4. See error.

## Expectation

On every reload, a card should always be selected.

## Screenshots

Here is the usecase with no card selected.
<img width="1879" alt="Screen Shot 2022-10-15 at 12 25 30" src="https://user-images.githubusercontent.com/44881714/195983985-3348a184-8fbd-4d21-963a-e0087b99e490.png">

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by adetyaz** [comment]
I think this is working now, I have tried it and it selects a card

**Comment by JennySimen** [comment]
@adetyaz it still does not always select a card. I can still find the usecase where no card is selected. 
I have also pulled from upstream to make sure I have the updated code but I still see the bug.

Since the numbers are randomly generated, try reloading multiple times

**Comment by adetyaz** [comment]
I'll do that and get back to you on it. @JennySimen

**Comment by adetyaz** [comment]
Yes its true, I just experienced it now @JennySimen, after reloading about 5 times.

Can I take a stab at it?

**Comment by JennySimen** [comment]
@adetyaz currently, the ticket still has to be evaluated. If the status changes to `ready for work`, you can ask @possumbilities to assign the ticket to you

**Comment by adetyaz** [comment]
Alright thank you.

**Comment by adetyaz** [comment]
@possumbilities please I need help, any changes I make to the search.js file doesn't reflect. I have also tried a console.log and alert yet no indication that there has been any changes on the file.

**Comment by possumbilities** [comment]
@adetyaz  Hi! I'm sorry you're having trouble, when working locally it is likely that your local cache is not clearing when you change the file. You'll have to clear your browser cache after changing the file to make sure the changes are reflected correctly.

**Comment by adetyaz** [comment]
Alright, I'll do that  and get back on it. thanks @possumbilities.

Side note: when I make changes to text on the interface it changes

**Comment by adetyaz** [comment]
@possumbilities, I still experience the same thing, after clearing the cache and using a new browser

**Comment by possumbilities** [comment]
@adetyaz Then, I'd suggest you try the [CC Community Slack](https://opensource.creativecommons.org/community/#slack) and ask there, to see if anyone else has had a similar issue, and how they resolved it.

**Comment by adetyaz** [comment]
Alright thank you

**Comment by JennySimen** [comment]
@adetyaz do you have any errors on your console? 
You can tag me on slack so as well so we debug together

**Comment by adetyaz** [comment]
@JennySimen yes I have a couple of them

**Comment by ImaJin14** [comment]
> @JennySimen yes I have a couple of them

Get to me on to get more insight

**Comment by JennySimen** [comment]
> > @JennySimen yes I have a couple of them
> 
> Get to me on to get more insight

@ImaJin14 we already solved found the source of the bugs and fixed it. You can check the conversation  on slack

**Comment by JennySimen** [comment]
@adetyaz The PR of #150 fixes this as well.

Just a heads up

**Comment by adetyaz** [comment]
oh okies, seen it. thanks

**Comment by JennySimen** [comment]
@possumbilities since there has been no fix for this issue yet can i go on to provide a fix for this or #108 fixes this as well.
